-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        rounding = 10,
    },
    general = {
        col = {
            active_border = {
                colors = {"rgba(33ccffee)", "rgba(f6bf47ff)"},
                angle = 60,
            },
            inactive_border = "0xaa595959",
        },
        gaps_out = 15,
    },
    misc = {
        disable_autoreload = false,
        disable_hyprland_logo = false,
        vrr = 1,
    },
})

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
